version: '2'

services:

  elasticsearch:
    image: elasticsearch:2
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/index:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro

  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
    volumes:
      - ./pg_data_build:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  pgbouncer:
    image: gavinmroy/alpine-pgbouncer:latest
    restart: always
    volumes:
      - ./config/pgbouncer:/etc/pgbouncer:ro
      - /etc/localtime:/etc/localtime:ro
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - 6432:6432

  django:
    build:
      context: .
      args:
        - OPACSSM_BUILD_DATE=${OPACSSM_BUILD_DATE}            # export OPACSSM_BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
        - OPACSSM_VCS_REF=${OPACSSM_VCS_REF}                  # export OPACSSM_VCS_REF=`git rev-parse --short HEAD`
        - OPACSSM_WEBAPP_VERSION=${OPACSSM_WEBAPP_VERSION}    # export OPACSSM_WEBAPP_VERSION="v0.1.0-dev"
    user: django
    restart: always
    depends_on:
      - pgbouncer
      - redis
      - elasticsearch
    command: /gunicorn.sh
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_SECRET_KEY=sdal#^4pih^ekewqtq8k_m9lin#136olq-_p086wsu-)=8=ns!
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=True
      - USE_DOCKER=yes
      - HAYSTACK_CONNECTIONS_HOST=elasticsearch
      - HAYSTACK_CONNECTIONS_PORT=9200
      - HAYSTACK_CONNECTIONS_INDEX=opac_ssm_idx
    volumes:
      - ./data/media:/app/opac_ssm/media
      - /etc/localtime:/etc/localtime:ro

  redis:
    image: redis:latest
    user: redis
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro

  celeryworker:
    build: .
    user: django
    restart: always
    depends_on:
      - postgres
      - redis
      - elasticsearch
    command: celery -A opac_ssm.taskapp worker -l INFO
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_SECRET_KEY=sdal#^4pih^ekewqtq8k_m9lin#136olq-_p086wsu-)=8=ns!
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=False
      - USE_DOCKER=yes
      - HAYSTACK_CONNECTIONS_HOST=elasticsearch
      - HAYSTACK_CONNECTIONS_PORT=9200
      - HAYSTACK_CONNECTIONS_INDEX=opac_ssm_idx
    volumes:
      - ./data/media:/app/opac_ssm/media
      - /etc/localtime:/etc/localtime:ro

  celerybeat:
    build: .
    user: django
    restart: always
    depends_on:
      - pgbouncer
      - redis
    command: celery -A opac_ssm.taskapp beat -l INFO
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_SECRET_KEY=sdal#^4pih^ekewqtq8k_m9lin#136olq-_p086wsu-)=8=ns!
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=False
      - USE_DOCKER=yes
      - HAYSTACK_CONNECTIONS_HOST=elasticsearch
      - HAYSTACK_CONNECTIONS_PORT=9200
      - HAYSTACK_CONNECTIONS_INDEX=opac_ssm_idx
    volumes:
      - ./data/media:/app/opac_ssm/media
      - /etc/localtime:/etc/localtime:ro

  grpc:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    user: django
    restart: always
    depends_on:
      - pgbouncer
      - redis
      - elasticsearch
    command: /start-grpc.sh
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DJANGO_SECRET_KEY=sdal#^4pih^ekewqtq8k_m9lin#136olq-_p086wsu-)=8=ns!
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=False
      - USE_DOCKER=yes
      - HAYSTACK_CONNECTIONS_HOST=elasticsearch
      - HAYSTACK_CONNECTIONS_PORT=9200
      - HAYSTACK_CONNECTIONS_INDEX=opac_ssm_idx
    volumes:
      - .:/app
      - ./data/media:/app/opac_ssm/media
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5000:5000"
